//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.ServiceReferenceTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTest.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rebelde del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddListServiceRebelde", ReplyAction="*")]
        UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeResponse AddListServiceRebelde(UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddListServiceRebelde", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeResponse> AddListServiceRebeldeAsync(UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetRebeldesServiceResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRebeldesService", ReplyAction="*")]
        UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceResponse GetRebeldesService(UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRebeldesService", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceResponse> GetRebeldesServiceAsync(UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento soldado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddListServiceSoldado", ReplyAction="*")]
        UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoResponse AddListServiceSoldado(UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddListServiceSoldado", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoResponse> AddListServiceSoldadoAsync(UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetSoldadosServiceResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSoldadosService", ReplyAction="*")]
        UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceResponse GetSoldadosService(UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSoldadosService", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceResponse> GetSoldadosServiceAsync(UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddListServiceRebeldeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddListServiceRebelde", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequestBody Body;
        
        public AddListServiceRebeldeRequest() {
        }
        
        public AddListServiceRebeldeRequest(UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddListServiceRebeldeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rebelde;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string planeta;
        
        public AddListServiceRebeldeRequestBody() {
        }
        
        public AddListServiceRebeldeRequestBody(string rebelde, string planeta) {
            this.rebelde = rebelde;
            this.planeta = planeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddListServiceRebeldeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddListServiceRebeldeResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeResponseBody Body;
        
        public AddListServiceRebeldeResponse() {
        }
        
        public AddListServiceRebeldeResponse(UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddListServiceRebeldeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddListServiceRebeldeResult;
        
        public AddListServiceRebeldeResponseBody() {
        }
        
        public AddListServiceRebeldeResponseBody(bool AddListServiceRebeldeResult) {
            this.AddListServiceRebeldeResult = AddListServiceRebeldeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRebeldesServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRebeldesService", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequestBody Body;
        
        public GetRebeldesServiceRequest() {
        }
        
        public GetRebeldesServiceRequest(UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRebeldesServiceRequestBody {
        
        public GetRebeldesServiceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRebeldesServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRebeldesServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceResponseBody Body;
        
        public GetRebeldesServiceResponse() {
        }
        
        public GetRebeldesServiceResponse(UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRebeldesServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestProject1.ServiceReferenceTest.ArrayOfString GetRebeldesServiceResult;
        
        public GetRebeldesServiceResponseBody() {
        }
        
        public GetRebeldesServiceResponseBody(UnitTestProject1.ServiceReferenceTest.ArrayOfString GetRebeldesServiceResult) {
            this.GetRebeldesServiceResult = GetRebeldesServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddListServiceSoldadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddListServiceSoldado", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequestBody Body;
        
        public AddListServiceSoldadoRequest() {
        }
        
        public AddListServiceSoldadoRequest(UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddListServiceSoldadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string soldado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string planeta;
        
        public AddListServiceSoldadoRequestBody() {
        }
        
        public AddListServiceSoldadoRequestBody(string soldado, string planeta) {
            this.soldado = soldado;
            this.planeta = planeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddListServiceSoldadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddListServiceSoldadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoResponseBody Body;
        
        public AddListServiceSoldadoResponse() {
        }
        
        public AddListServiceSoldadoResponse(UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddListServiceSoldadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddListServiceSoldadoResult;
        
        public AddListServiceSoldadoResponseBody() {
        }
        
        public AddListServiceSoldadoResponseBody(bool AddListServiceSoldadoResult) {
            this.AddListServiceSoldadoResult = AddListServiceSoldadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSoldadosServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSoldadosService", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequestBody Body;
        
        public GetSoldadosServiceRequest() {
        }
        
        public GetSoldadosServiceRequest(UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSoldadosServiceRequestBody {
        
        public GetSoldadosServiceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSoldadosServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSoldadosServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceResponseBody Body;
        
        public GetSoldadosServiceResponse() {
        }
        
        public GetSoldadosServiceResponse(UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSoldadosServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTestProject1.ServiceReferenceTest.ArrayOfString GetSoldadosServiceResult;
        
        public GetSoldadosServiceResponseBody() {
        }
        
        public GetSoldadosServiceResponseBody(UnitTestProject1.ServiceReferenceTest.ArrayOfString GetSoldadosServiceResult) {
            this.GetSoldadosServiceResult = GetSoldadosServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : UnitTestProject1.ServiceReferenceTest.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<UnitTestProject1.ServiceReferenceTest.WebServiceSoap>, UnitTestProject1.ServiceReferenceTest.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeResponse UnitTestProject1.ServiceReferenceTest.WebServiceSoap.AddListServiceRebelde(UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequest request) {
            return base.Channel.AddListServiceRebelde(request);
        }
        
        public bool AddListServiceRebelde(string rebelde, string planeta) {
            UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequest inValue = new UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequest();
            inValue.Body = new UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequestBody();
            inValue.Body.rebelde = rebelde;
            inValue.Body.planeta = planeta;
            UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeResponse retVal = ((UnitTestProject1.ServiceReferenceTest.WebServiceSoap)(this)).AddListServiceRebelde(inValue);
            return retVal.Body.AddListServiceRebeldeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeResponse> UnitTestProject1.ServiceReferenceTest.WebServiceSoap.AddListServiceRebeldeAsync(UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequest request) {
            return base.Channel.AddListServiceRebeldeAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeResponse> AddListServiceRebeldeAsync(string rebelde, string planeta) {
            UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequest inValue = new UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequest();
            inValue.Body = new UnitTestProject1.ServiceReferenceTest.AddListServiceRebeldeRequestBody();
            inValue.Body.rebelde = rebelde;
            inValue.Body.planeta = planeta;
            return ((UnitTestProject1.ServiceReferenceTest.WebServiceSoap)(this)).AddListServiceRebeldeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceResponse UnitTestProject1.ServiceReferenceTest.WebServiceSoap.GetRebeldesService(UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequest request) {
            return base.Channel.GetRebeldesService(request);
        }
        
        public UnitTestProject1.ServiceReferenceTest.ArrayOfString GetRebeldesService() {
            UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequest inValue = new UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequest();
            inValue.Body = new UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequestBody();
            UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceResponse retVal = ((UnitTestProject1.ServiceReferenceTest.WebServiceSoap)(this)).GetRebeldesService(inValue);
            return retVal.Body.GetRebeldesServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceResponse> UnitTestProject1.ServiceReferenceTest.WebServiceSoap.GetRebeldesServiceAsync(UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequest request) {
            return base.Channel.GetRebeldesServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceResponse> GetRebeldesServiceAsync() {
            UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequest inValue = new UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequest();
            inValue.Body = new UnitTestProject1.ServiceReferenceTest.GetRebeldesServiceRequestBody();
            return ((UnitTestProject1.ServiceReferenceTest.WebServiceSoap)(this)).GetRebeldesServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoResponse UnitTestProject1.ServiceReferenceTest.WebServiceSoap.AddListServiceSoldado(UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequest request) {
            return base.Channel.AddListServiceSoldado(request);
        }
        
        public bool AddListServiceSoldado(string soldado, string planeta) {
            UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequest inValue = new UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequest();
            inValue.Body = new UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequestBody();
            inValue.Body.soldado = soldado;
            inValue.Body.planeta = planeta;
            UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoResponse retVal = ((UnitTestProject1.ServiceReferenceTest.WebServiceSoap)(this)).AddListServiceSoldado(inValue);
            return retVal.Body.AddListServiceSoldadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoResponse> UnitTestProject1.ServiceReferenceTest.WebServiceSoap.AddListServiceSoldadoAsync(UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequest request) {
            return base.Channel.AddListServiceSoldadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoResponse> AddListServiceSoldadoAsync(string soldado, string planeta) {
            UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequest inValue = new UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequest();
            inValue.Body = new UnitTestProject1.ServiceReferenceTest.AddListServiceSoldadoRequestBody();
            inValue.Body.soldado = soldado;
            inValue.Body.planeta = planeta;
            return ((UnitTestProject1.ServiceReferenceTest.WebServiceSoap)(this)).AddListServiceSoldadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceResponse UnitTestProject1.ServiceReferenceTest.WebServiceSoap.GetSoldadosService(UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequest request) {
            return base.Channel.GetSoldadosService(request);
        }
        
        public UnitTestProject1.ServiceReferenceTest.ArrayOfString GetSoldadosService() {
            UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequest inValue = new UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequest();
            inValue.Body = new UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequestBody();
            UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceResponse retVal = ((UnitTestProject1.ServiceReferenceTest.WebServiceSoap)(this)).GetSoldadosService(inValue);
            return retVal.Body.GetSoldadosServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceResponse> UnitTestProject1.ServiceReferenceTest.WebServiceSoap.GetSoldadosServiceAsync(UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequest request) {
            return base.Channel.GetSoldadosServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceResponse> GetSoldadosServiceAsync() {
            UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequest inValue = new UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequest();
            inValue.Body = new UnitTestProject1.ServiceReferenceTest.GetSoldadosServiceRequestBody();
            return ((UnitTestProject1.ServiceReferenceTest.WebServiceSoap)(this)).GetSoldadosServiceAsync(inValue);
        }
    }
}
